# Generated by Django 3.1 on 2020-08-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silk', '0007_sqlquery_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlquery',
            name='query_structure',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
